apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noaa-etl

resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - airflow/configmap.yaml
  - airflow/deployment.yaml
  - airflow/service.yaml
  - spark/master-deployment.yaml
  - spark/worker-deployment.yaml
  - spark/services.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - monitoring/service-monitor.yaml
  - secrets/external-secret.yaml
