apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark
    component: master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8081
      targetPort: 8081
